In [2]:
from IPython.display import Image

# 텐서란
- tensor는 딥러닝에가 가장 기본이 되는 단위중 하나이다. 
- ![](../img/tensor.png)
- 각 값을 메모리에 저장할 때 스칼라는 하나의 변수로 나타낼 수 있고
- 벡터는 1차원의 배열로 나타낼 수 있다.
- 행렬은 2차원의 배열로 나타낸다.
- 텐서부터는 3차원 이상의 배열로 나타낸다.


## 행렬의 표현
- x는 k개의 행과 n개의 열로 이루어져 있다.

## 텐서의 표현
- K X n X m 차원의 텐서
- 첫번째 차원 k가 세로축의 크기를 나타냄
- n 이 가로축의 차원을 나타냄
- m 이 마지막 남은 축의 차원을 나타냄

## 파이토치 텐서 생성하기

In [4]:
import torch

tf = torch.FloatTensor([[1,2],[3,4]])
tf

tensor([[1., 2.],
        [3., 4.]])

In [6]:
lt = torch.LongTensor([[1,2],[3,4]])
lt

tensor([[1, 2],
        [3, 4]])

In [8]:
bt = torch.ByteTensor([[1,0],[0,1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [9]:
x = torch.FloatTensor(3,2)
x

tensor([[0.0000e+00, 7.9874e-44],
        [2.0547e+20, 3.3089e-09],
        [8.1804e+20, 3.3794e+21]])

## 넘파이 호환

In [15]:
import numpy as np

x = np.array([[1,2],[3,4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [16]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [17]:
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## 텐서 타입 변환

In [18]:
tf.long()

tensor([[1, 2],
        [3, 4]])

In [20]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

## 텐서 크기 구하기

In [21]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                        [[5,6],
                        [7,8]],
                        [[9,10],
                        [11,12]]])

In [22]:
# size()함수의 결괏값이 shape속성에 담겨있다.
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [23]:
print(x.size(1))
print(x.shape[1])

2
2


In [24]:
print(x.size(-1))
print(x.shape[-1])

2
2


In [25]:
print(x.dim())
print(len(x.size()))

3
3
