In [1]:
import torch

## 요소별 산술 연산

In [2]:
a = torch.FloatTensor([[1,2],[3,4]])
b = torch.FloatTensor([[2,2], [3,3]])

In [3]:
a+b

tensor([[3., 4.],
        [6., 7.]])

In [4]:
a-b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [5]:
a*b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [6]:
a/b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [7]:
a**b

tensor([[ 1.,  4.],
        [27., 64.]])

In [8]:
a==b

tensor([[False,  True],
        [ True, False]])

In [9]:
a!=b

tensor([[ True, False],
        [False,  True]])

## 인플레이스 연산
- 기존 텐서에 결과가 저장된다
- 파이토치측은 가비지 컬렉터가 효율적으로 작동하기 때무에 굳이 인플레이스 연산을 사용할 필요는 없다.

In [10]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [11]:
print(a.mul(b))

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [12]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [13]:
print(a.mul_(b)) #여기가 포인트

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [14]:
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])


## 차원축소연산:합과 평균

In [15]:
x = torch.FloatTensor([[1,2],[3,4]])

In [16]:
print(x.sum())

tensor(10.)


In [17]:
print(x.mean())

tensor(2.5000)


In [19]:
print(x.sum(dim=0))
# dim 인자의 값은 없어지는 차춴이라고 생각하면 쉽다.
# dim=0이면 첫번째 차원을 이야기 하는 것이므로 행렬의 세로축에 대하여 합연산을 수행한다.

tensor([4., 6.])


In [20]:
print(x.sum(dim=-1))

tensor([3., 7.])


## 브로드캐스트 연산
- 크기가 다른 두 텐서를 가지고 산술 연산을 수행하면 어떻게 될까?

### 텐서 + 스칼라

In [21]:
x = torch.FloatTensor([[1,2],[3,4]])
y=1

In [22]:
z = x+y
print(z)

tensor([[2., 3.],
        [4., 5.]])


In [23]:
print(z.size())

torch.Size([2, 2])


### 텐서+텐서

In [24]:
x = torch.FloatTensor([[1,2],[4,8]])
y = torch.FloatTensor([3,5])
print(x.size())

torch.Size([2, 2])


In [25]:
print(y.size())

torch.Size([2])


In [26]:
z = x+y
print(z)

tensor([[ 4.,  7.],
        [ 7., 13.]])


In [27]:
print(z.size())

torch.Size([2, 2])


In [28]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([3,5])
print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2])


In [29]:
z = x+y
print(z)

tensor([[4., 7.]])


In [30]:
x = torch.FloatTensor([[1,2]])
x = torch.FloatTensor([[3],[5]])
print(x.size())
print(y.size())

torch.Size([2, 1])
torch.Size([2])


In [31]:
z = x + y
print(z)
print(z.size())

tensor([[ 6.,  8.],
        [ 8., 10.]])
torch.Size([2, 2])
