# 텐서 형태 변환
- 텐서의 전체 요소 개수는 유지한 채 모양을 바꾸는 방법을 알아보겠다.

In [1]:
import torch

## View 함수
- view 함수를 통해 형태 변환을 수행한다.
- view 함수의 인자로는 원하는 텐서의 크기를 넣어주면 된다.
- 여기에서 중요한 점은 텐서의 요소 개수는 유지되어야 한다.
- view 함수는 메모리에 순차대로 선언된 텐서에 대해서만 동작한다..
- 만약 해당 조건에 만족하지 않는다면 오류를 발생시킨다.

In [4]:
x = torch.FloatTensor([[[1,2],[3,4]],
                        [[5,6],[7,8]],
                        [[9,19],[11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [5]:
print(x.view(12))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 19., 11., 12.])


In [6]:
print(x.view(3,1,4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 19., 11., 12.]]])


In [7]:
print(x.view(-1))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 19., 11., 12.])


In [8]:
print(x.view(3,-1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 19., 11., 12.]])


In [9]:
print(x.view(-1,1,4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 19., 11., 12.]]])


In [11]:
y = x.view(3,4)
x.storage().data_ptr()==y.storage().data_ptr()

True

In [13]:
# 텐서 형태 변환을 진행하고 싶다면 contiguous 함수를 호출한후 view함수를 호출하면된다.
# contiguous함수는 텐서를 새로운 메모리상의 인접한 주소에 인접한 값을 순서대로 할당해주는 함수이다.
# 이미 메로리상에 원하는 형태로 존재한다면 새롭게 할당하지 않고 해당 텐서를 contiguous 함수의 결괏값으로 그대로 반환한다.
# reshape함수는 contiguous함수와 view함수를 순차적으로 호출한다.
print(x.reshape(3,4))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 19., 11., 12.]])


## Squeeze 함수
- 차원의 크기가 1인 차원을 없애주는 역할을 한다.
- 원하는 차원의 인덱스를 저장할 수 있다.
- 만약 해당 차원의 크기가 1이아닌 경우 같은 텐서를 반환하게 된다.

In [14]:
x = torch.FloatTensor([[[1,2],[3,4]]])
print(x.size())

torch.Size([1, 2, 2])


In [15]:
print(x.squeeze())

tensor([[1., 2.],
        [3., 4.]])


In [16]:
print(x.squeeze().size())

torch.Size([2, 2])


In [18]:
print(x.squeeze(0).size())

torch.Size([2, 2])


In [19]:
print(x.squeeze(1).size())

torch.Size([1, 2, 2])


## Unsqueeze 함수
- squeeze의 반대 역할을 수행하는 함수
- 지정된 차원의 인덱스에 차원의 크기가 1인 차원을 삽입한다.

In [21]:
x = torch.FloatTensor([[1,2],[3,4]])
print(x.size())

torch.Size([2, 2])


In [22]:
print(x.unsqueeze(1).size())
print(x.unsqueeze(-1).size())
print(x.unsqueeze(2).size())

torch.Size([2, 1, 2])
torch.Size([2, 2, 1])
torch.Size([2, 2, 1])


In [23]:
print(x.reshape(2,2,-1).size())

torch.Size([2, 2, 1])
