# 텐서 자르기 & 붙이기

In [1]:
import torch

## 인덱싱과 슬라이싱

In [2]:
x = torch.FloatTensor([[[1,2],[3,4]],
                        [[5,6],[7,8]],
                        [[9,10],[11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [3]:
print(x[0])

tensor([[1., 2.],
        [3., 4.]])


In [4]:
print(x[-1])

tensor([[ 9., 10.],
        [11., 12.]])


In [5]:
print(x[:,0])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [6]:
print(x[1:2,1:,:].size())

torch.Size([1, 1, 2])


## Split 함수
- 텐서를 특정 차원에 대해서 원하는 크기로 잘라준다.

In [7]:
x = torch.FloatTensor(10,4)
splits = x.split(4, dim=0)

In [8]:
for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


## chunk 함수
- split 함수는 개수에 상관없이 원하는 크기로 나누었다면 
- 크기에 상관없이 원하는 개수로 나누는 chunk함수를 다뤄보겠다.

In [9]:
x = torch.FloatTensor(8,4)

In [10]:
chunks = x.chunk(3, dim=0)
for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


## Index Select 함수
- 특정 차원에서는 원하는 인덱스의 값만 취하는 함수이다.

In [11]:
x = torch.FloatTensor([[[1,1],[2,2]],
                        [[3,3],[4,4]],
                        [[5,5],[6,6]]])
indice = torch.LongTensor([2,1])
print(x.size())

torch.Size([3, 2, 2])


In [12]:
y = x.index_select(dim=0, index=indice)
print(y)

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])


In [13]:
print(y.size())

torch.Size([2, 2, 2])


## Concatenate함수
- 여러 텐서를 합쳐서 하나의 텐서로 만드는 방법
- 두 개 이상의 텐서를 순서대로 합쳐서 하나의 텐서로 반환한다.
- 합쳐지기 위해서는 다른 차원들의 크기가 같아야 한다.