# 텐서 자르기 & 붙이기

In [1]:
import torch

## 인덱싱과 슬라이싱

In [2]:
x = torch.FloatTensor([[[1,2],[3,4]],
                        [[5,6],[7,8]],
                        [[9,10],[11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [3]:
print(x[0])

tensor([[1., 2.],
        [3., 4.]])


In [4]:
print(x[-1])

tensor([[ 9., 10.],
        [11., 12.]])


In [5]:
print(x[:,0])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [6]:
print(x[1:2,1:,:].size())

torch.Size([1, 1, 2])


## Split 함수
- 텐서를 특정 차원에 대해서 원하는 크기로 잘라준다.

In [7]:
x = torch.FloatTensor(10,4)
splits = x.split(4, dim=0)

In [8]:
for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


## chunk 함수
- split 함수는 개수에 상관없이 원하는 크기로 나누었다면 
- 크기에 상관없이 원하는 개수로 나누는 chunk함수를 다뤄보겠다.

In [9]:
x = torch.FloatTensor(8,4)

In [10]:
chunks = x.chunk(3, dim=0)
for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


## Index Select 함수
- 특정 차원에서는 원하는 인덱스의 값만 취하는 함수이다.

In [11]:
x = torch.FloatTensor([[[1,1],[2,2]],
                        [[3,3],[4,4]],
                        [[5,5],[6,6]]])
indice = torch.LongTensor([2,1])
print(x.size())

torch.Size([3, 2, 2])


In [12]:
y = x.index_select(dim=0, index=indice)
print(y)

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])


In [13]:
print(y.size())

torch.Size([2, 2, 2])


## Concatenate함수
- 여러 텐서를 합쳐서 하나의 텐서로 만드는 방법
- 두 개 이상의 텐서를 순서대로 합쳐서 하나의 텐서로 반환한다.
- 합쳐지기 위해서는 다른 차원들의 크기가 같아야 한다.

In [14]:
x = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
y = torch.FloatTensor([[10,11,12],[13,14,15],[16,17,18]])
print(x.size(), y.size())


torch.Size([3, 3]) torch.Size([3, 3])


In [15]:
z = torch.cat([x,y],dim=0)
print(z)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])


In [16]:
print(z.size())

torch.Size([6, 3])


In [17]:
z = torch.cat([x,y],dim=-1)
print(z)

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])


In [18]:
print(z.size())

torch.Size([3, 6])


## Stack 함수
- cat함수와 비슷한 역할을 수행하는 stack 함수
- 이어 붙이기 작업을 수행한느 것이 아니라 쌓기 작업을 수행한다
- 새로운 차원을 만둔 뒤에 이어붙이기를 수행

In [19]:
z = torch.stack([x,y])
print(z)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])


In [20]:
print(z.size())

torch.Size([2, 3, 3])


In [21]:
z = torch.stack([x,y], dim=-1)
print(z)

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])


In [22]:
print(z.size())

torch.Size([3, 3, 2])


In [23]:
d = 0
# z = torch.stack([x,y],dim=d)
z = torch.cat([x.unsqueeze(d), y.unsqueeze(d)], dim=d)
print(z)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])


In [25]:
print(z.size())

torch.Size([2, 3, 3])


## 유용한 팁
- cat 함수나 stack함수는 실전에서 매우 유용하게 활용될 때가 많다.
- 특히 여러 이터레이션(iteration)을 돌며 반복되는 작업을 수행한 후 반복 작업의 결과물을 하나로 합치는데 사용한다.

In [27]:
result = []
for i in range(5):
    x = torch.FloatTensor(2,2)
    result += [x]

result = torch.stack(result)
print(result)

tensor([[[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[1.0500e-08, 1.3226e-08],
         [1.7079e-07, 4.5908e-41]],

        [[1.0477e-08, 1.3226e-08],
         [8.1264e-25, 4.5908e-41]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[1.0477e-08, 1.3226e-08],
         [8.1264e-25, 4.5908e-41]]])
