In [1]:
import torch

## Expand 함수
- 차원의 크기가 1인 차원을 원하는 크기로 늘려주는 역할을 수행
- 동일한 텐서를 그냥 반복하여 리스트에 넣고 cat 함수를 해당 차원에 대해 수행하는 것과 같다.

In [4]:
x = torch.FloatTensor([[[1,2]],[[3,4]]])
print(x.size())

torch.Size([2, 1, 2])


In [7]:
y = x.expand(2,3,2)
print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


In [8]:
y = torch.cat([x]*3,dim=1)
print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


## Random Permutation 함수
- 랜덤 수열을 생성하는 파치토치 함수

In [9]:
x = torch.randperm(10)
print(x)


tensor([3, 5, 7, 9, 4, 8, 1, 0, 2, 6])


In [10]:
print(x.size())

torch.Size([10])


## Argument Max 함수
- 함수 f의 출력값을 최대로 만드는 입력을 반환하는 함수이다.
- 중요한 점은 f의 최댓값을 반환하는 것이 아니라 f를 최대로 만드는 x값을 반환한다는 것이다.

In [11]:
x = torch.randperm(3**3).reshape(3,3,-1)
print(x)

tensor([[[19, 25,  5],
         [ 9,  8, 10],
         [20, 26,  4]],

        [[13,  7, 15],
         [ 3, 21, 11],
         [14,  1,  0]],

        [[17,  2, 18],
         [22, 12, 24],
         [23,  6, 16]]])


In [12]:
print(x.size())

torch.Size([3, 3, 3])


In [13]:
# 인덱스를 -1로 지정해주었기 때문에 다른 차원들이 같은 값 중에서 가장 큰 값의 인덱스를 반환
y = x.argmax(dim=-1)
print(y)


tensor([[1, 2, 1],
        [2, 1, 0],
        [2, 2, 0]])


In [14]:
print(y.size())

torch.Size([3, 3])


## Top-k함수
- argmax의 상위 호환 버전
- argmax는 가장 큰 한 개의 값의 인덱스를 반환하는 것이었다면
- topk 함수는 가장 큰 k 개의 의 인덱스를 모두 반환한다.

In [15]:
values, indices = torch.topk(x,k=1,dim=-1)
print(values.size())
print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


In [16]:
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size())

torch.Size([3, 3, 2])


## Sort함수


In [17]:
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size())

torch.Size([3, 3, 2])


In [18]:
target_dim = -1
values, indices = torch.topk(x, k=x.size(target_dim), largest=True)
print(values)

tensor([[[25, 19,  5],
         [10,  9,  8],
         [26, 20,  4]],

        [[15, 13,  7],
         [21, 11,  3],
         [14,  1,  0]],

        [[18, 17,  2],
         [24, 22, 12],
         [23, 16,  6]]])


## Masked File 함수
- 텐서 내의 원하는 부분만 특정 값으로 바꿔치기하는 함수


In [19]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3,-1)
print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [21]:
mask = x > 4
print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [23]:
y = x.masked_fill(mask,value=-1)
print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


## Ones & Zeros 함수

In [24]:
print(torch.ones(2,3))
print(torch.zeros(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [25]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
print(x.size())
print(torch.ones_like(x))
print(torch.zeros_like(x))

torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
