# 선형계층
- 행렬 곱셈과 벡터의 덧셈으로 이루어져 있기 때문에 선형 변환이라고 볼 수 있다.
- 따라서 선형 계층을 통해 모델을 구성할 경우에는 선형 데이터에 대한 관계를 분석하거나 선형 함수를 근사계산할수 있다.

In [1]:
import torch

In [2]:
W = torch.FloatTensor([[1,2],[3,4],[5,6]])
b = torch.FloatTensor([2,2])

In [3]:
def linear(x,W,b):
    y = torch.matmul(x, W) + b
    return y

In [4]:
x = torch.FloatTensor(4,3)

In [5]:
y = linear(x,W,b)
print(y.size())

torch.Size([4, 2])


## torch.nn.Module 클래스상속받기
- 파이토치에는 nn(neural networks)패키지가 있고 내부에는 미리 정의된 많은 신경망들이 있다.
- 그리고 그 신경망들은 torch.nn.Module이라는 추상 클래스를 상속받아 정의되어있다.
- 바로 이 추상 클래스를 상속받아 선형 계층을 구현할 수 있다.

In [6]:
import torch.nn as nn

> nn.Module를 상속받으면 보통 2개의 메서드 __init__과 forward를 오버라이드한다.<br>
> __init__ 함수는 계층 내부에서 필요한 변수를 미리 선언하고 있으며 심지어 또 다른 계층을 소유하도록 할 수 있다.<br>
> forward함수는 계층을 통과하는데 필요한 계산 수행을 한다.

In [9]:
class MyLinear(nn.Module):
    
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

    # You should overrid 'forward' method to implement detail
    # The input argments and outputs can be designed as you wish.
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        # |y| = (batch.size, input_dim) * (input_dim, output_dim)
        # = (batch_size, output_dim)

        return y

In [10]:
linear = MyLinear(3,2)

In [11]:
# forward 함수를 따로 호출하지 않고 객체명에 바로 괄호를 열어 텐서 x를 인수로 넘겨주었다.
# 이처럼 nn.Module의 상속받은 객체는 __call__함수와 forward가 매핑되어 있어서 forward를 직접 부를 필요가 없다.
# forward 호출 앞뒤로 추가적으로 호출하는 함수가 파이토치 내부에 따로 있기 때문에 사용자가 직접 forward 함수를 호출하는 것을 권장하지 않는다.
y = linear(x)

In [13]:
for p in linear.parameters():
    print(p)

## 올바른 방법 : nn.Parameter 활용하기

In [18]:
class MyLinear(nn.Module):
    
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))

    # You should overrid 'forward' method to implement detail
    # The input argments and outputs can be designed as you wish.
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        # |y| = (batch.size, input_dim) * (input_dim, output_dim)
        # = (batch_size, output_dim)

        return y
linear = MyLinear(3,2)
y = linear(x)

In [19]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


## nn.Linear 활용하기

In [22]:
class MyLinear(nn.Module):
    
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.linear = nn.Linear(input_dim, output_dim)

    # You should overrid 'forward' method to implement detail
    # The input argments and outputs can be designed as you wish.
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = self.linear(x)
        # |y| = (batch.size, input_dim) * (input_dim, output_dim)
        # = (batch_size, output_dim)

        return y
linear = MyLinear(3,2)
y = linear(x)

In [23]:
print(y)

tensor([[-0.3912, -0.3466],
        [-0.3912, -0.3466],
        [-0.3912, -0.3466],
        [-0.3912, -0.3466]], grad_fn=<AddmmBackward0>)
