# GPU사용하기
- 딥러닝 연산은 보통 엔비디아 그래픽처리장치에서 이루어진다.
- GPU를 통한 프로그래밍이 가능하도록 CUDA를 지원하고 있다.

## CUDA 함수

In [1]:
import torch

In [ ]:
x = torch.cuda.FloatTensor(2,2)

In [ ]:
x = torch.FloatTensor(2,2)
x = x.cuda()

In [ ]:
x = x.cuda(device=1)
x

In [ ]:
import torch.nn as nn
layer = nn.Linear(2,2)
layer.cuda(0)

## 서로 다른 장치간 연산

In [6]:
x = torch.FloatTensor(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
x + x.cuda(0)

## CPU 함수

In [ ]:
x = torch.cuda.FloatTensor(2,2)
x

In [8]:
x = x.cpu()
x

tensor([[0., 0.],
        [0., 0.]])

## To 함수
- 원하는 디바이스의 정보를 담은 객체를 인자로 받아
- 함수 자신을 호출한 객체를 해당 디바이스로 복사 시킨다.
- 디바이스 정보를 담은 객체는 torch.device를 통해 생성할 수 있다.

In [9]:
cpu_device = torch.device('cpu')
gpu_device = torch.device('coda:0')

In [10]:
x = torch.FloatTensor(2,2)
x

tensor([[-1.6724e-12,  9.9492e-43],
        [ 5.7397e-42,  0.0000e+00]])

In [ ]:
x = x.to(gpu_device)

In [12]:
x = x.to(cpu_device)
x

tensor([[-1.6724e-12,  9.9492e-43],
        [ 5.7397e-42,  0.0000e+00]])

## Device 속성

In [ ]:
x = torch.cuda.FloatTensor(2,2)
x.device

In [13]:
layer = nn.Linear(2,2)
next(layer.parameters()).device

device(type='cpu')