In [1]:
import torch
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.3,.4,.5],
                            [.7, .8, .9]])

In [3]:
x = torch.rand_like(target)
x.requires_grad = True
print(x)

tensor([[0.1550, 0.8439, 0.7339],
        [0.8652, 0.5077, 0.3989],
        [0.0263, 0.4722, 0.7065]], requires_grad=True)


In [4]:
loss = F.mse_loss(x, target)
loss

tensor(0.1718, grad_fn=<MseLossBackward0>)

In [5]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    loss.backward() # 편미분을 수행함 x.grad에 자동저장됨
    # backward를 호출하기 위한 텐서의 크기는 스칼라여야한다. 스칼라가 아닌경우 파이토치는 오류를 발생시킨다.

    x = x - learning_rate * x.grad # 경사하강법 수행

    x.detach_()
    x.requires_grad_(True)

    loss = F.mse_loss(x, target)

    print("%d-th Loss : %.4e" % (iter_cnt, loss))
    print(x)

1-th Loss : 1.0391e-01
tensor([[0.1428, 0.7008, 0.6375],
        [0.7396, 0.4838, 0.4213],
        [0.1760, 0.5450, 0.7495]], requires_grad=True)
2-th Loss : 6.2862e-02
tensor([[0.1333, 0.5895, 0.5625],
        [0.6419, 0.4651, 0.4388],
        [0.2925, 0.6017, 0.7830]], requires_grad=True)
3-th Loss : 3.8027e-02
tensor([[0.1259, 0.5030, 0.5042],
        [0.5659, 0.4507, 0.4524],
        [0.3830, 0.6457, 0.8090]], requires_grad=True)
4-th Loss : 2.3004e-02
tensor([[0.1201, 0.4356, 0.4588],
        [0.5068, 0.4394, 0.4630],
        [0.4535, 0.6800, 0.8292]], requires_grad=True)
5-th Loss : 1.3916e-02
tensor([[0.1156, 0.3833, 0.4235],
        [0.4609, 0.4307, 0.4712],
        [0.5083, 0.7067, 0.8449]], requires_grad=True)
6-th Loss : 8.4184e-03
tensor([[0.1122, 0.3426, 0.3961],
        [0.4251, 0.4238, 0.4776],
        [0.5509, 0.7274, 0.8572]], requires_grad=True)
7-th Loss : 5.0926e-03
tensor([[0.1095, 0.3109, 0.3747],
        [0.3973, 0.4185, 0.4826],
        [0.5840, 0.7436, 0.8667]]