# 파이토치 오토그래도 스개
- 요새 나오는 딥러닝 프레임워크들은 모두 자동 미분 기능을 제공한다.
- 파이토치에도 오토그래드라는 자동 미분 기능을 제공한다.
    - requires_grad 속성이 True인 텐서의 연산을 추적하기 위한 계산 그래프를 구축하고
    - backward 함수가 호출되면 이 그래프를 따라 미분을 자동으로 수행하고 계산된 그래디언트를 채워 놓는다.
    

In [9]:
import torch
x = torch.FloatTensor([[1,2], [3,4]]).requires_grad_(True)

In [10]:
x1 = x + 2
print(x1)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)


In [11]:
x2 = x-2
print(x2)

tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)


In [12]:
x3 = x1 * x2
print(x3)

tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)


In [13]:
y = x3.sum()
print(y)

tensor(14., grad_fn=<SumBackward0>)


- 모두 grad_fn 속성을 갖는다.

In [14]:
y.backward()

In [15]:
print(x.grad)                             

tensor([[2., 4.],
        [6., 8.]])


In [16]:
x3.detach_() # detach함수를 토앻 그래프로부터 떼어낼 수 있다.

tensor([[-3.,  0.],
        [ 5., 12.]])